name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
